### ISSUE TITLE
Geom invalid on search_interaction()

### ISSUE THREAD

**Issue by SteveViss** [ropensci/rmangal#77] opened 2019-07-29 15:44 UTC
```r
> foodwebs <- search_interactions(type = "predation")
`type` is used thus `query` is ignored.
                                                                    Found 64617 interactions
> foodwebs
Simple feature collection with 64617 features and 19 fields (with 22033 geometries empty)
geometry type:  POINT
dimension:      XY
bbox:           xmin: 31.46008 ymin: -89.49741 xmax: 53.91219 ymax: 11.58333
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
First 10 features:
       id node_from node_to                     date direction      type method
1  123153     31904   31863 2003-06-01T00:00:00.000Z  directed predation  model
2  123155     31904   31865 2003-06-01T00:00:00.000Z  directed predation  model
3  123157     31904   31867 2003-06-01T00:00:00.000Z  directed predation  model
4  123159     31904   31869 2003-06-01T00:00:00.000Z  directed predation  model
5  123161     31904   31872 2003-06-01T00:00:00.000Z  directed predation  model
6  123163     31904   31874 2003-06-01T00:00:00.000Z  directed predation  model
7  123165     31904   31877 2003-06-01T00:00:00.000Z  directed predation  model
8  123167     31904   31880 2003-06-01T00:00:00.000Z  directed predation  model
9  123173     31914   31913 2004-06-01T00:00:00.000Z  directed predation  model
10 123179     31916   31913 2004-06-01T00:00:00.000Z  directed predation  model
   attr_id  value public network_id               created_at
1       40 0.0020   TRUE       2470 2019-03-27T14:00:51.720Z
2       40 0.0190   TRUE       2470 2019-03-27T14:00:51.990Z
3       40 0.0050   TRUE       2470 2019-03-27T14:00:52.255Z
4       40 0.0200   TRUE       2470 2019-03-27T14:00:52.520Z
5       40 0.0050   TRUE       2470 2019-03-27T14:00:52.788Z
6       40 0.0079   TRUE       2470 2019-03-27T14:00:53.076Z
7       40 0.0250   TRUE       2470 2019-03-27T14:00:53.426Z
8       40 0.0070   TRUE       2470 2019-03-27T14:00:53.832Z
9       40 0.3000   TRUE       2471 2019-03-27T14:14:25.239Z
10      40 0.4000   TRUE       2471 2019-03-27T14:14:26.605Z
```

**Comment by KevCaz** [comment] 2019-07-30 19:04
Not a bug related to the R package - was related to the API and it is now fixed.

**Closed as completed by KevCaz** 2019-07-30 19:04 UTC
Labels: bug
